import turtle as trtl

pacman = trtl.Turtle()
pacman.speed(3)

pacman.penup()
pacman.goto(0,-42.5)
pacman.fillcolor('yellow')
pacman.setheading(90+45+180)
pacman.pendown()
pacman.begin_fill()
pacman.circle(60,180)
pacman.end_fill()

pacman.penup()
pacman.goto(0,42.5)
pacman.fillcolor('yellow')
pacman.setheading(45+180)
pacman.pendown()
pacman.begin_fill()
pacman.circle(60,-180)
pacman.end_fill()

pacman.penup()
pacman.goto(45,40)
pacman.fillcolor('black')
pacman.pendown()
pacman.begin_fill()
pacman.circle(5)
pacman.end_fill()

pacman.penup()
pacman.setheading(45)
pacman.goto(0,-42.5)
pacman.pencolor("red")
pacman.pendown()
pacman.pensize(5)
pacman.forward(25)

pacman.penup()
pacman.setheading(-45)
pacman.goto(0,42.5)
pacman.pencolor("red")
pacman.pendown()
pacman.pensize(5)
pacman.forward(25)

pacman.penup()
pacman.setheading(-40)
pacman.goto(50,70)
pacman.pencolor("red")
pacman.fillcolor('red')
pacman.pendown()
pacman.begin_fill()
pacman.pensize(2)
pacman.forward(70)
pacman.setheading(80)
pacman.forward(20)
pacman.setheading(170)
pacman.forward(70)
# pacman.setheading(120)
# pacman.forward(20)
pacman.goto(50,70)
pacman.end_fill()


step=0
for i in range(10):
  pacman.penup()
  pacman.goto(0-step,4)
  pacman.fillcolor('yellow')
  pacman.pendown()
  pacman.begin_fill()
  pacman.circle(8)
  pacman.end_fill()
  step+=25

pacman.penup()
pacman.goto(-255,0)
pacman.fillcolor('red')
pacman.setheading(90)
pacman.pendown()
pacman.begin_fill()
pacman.circle(24)
pacman.end_fill()
pacman.pencolor("black")
pacman.penup()
pacman.goto(-275,12)
pacman.setheading(90)
pacman.pensize(7)
pacman.pendown()
pacman.circle(48,70)


wn = trtl.Screen()
wn.mainloop()